//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Data.Entity.Core.Objects;
using System.Linq;

public partial class UserLoginDBEntities : DbContext
{
    public UserLoginDBEntities()
        : base("name=UserLoginDBEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<User> User { get; set; }

    public virtual int PASSWORD_CONTROL(string pASSWORD)
    {
        var pASSWORDParameter = pASSWORD != null ?
            new ObjectParameter("PASSWORD", pASSWORD) :
            new ObjectParameter("PASSWORD", typeof(string));

        return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PASSWORD_CONTROL", pASSWORDParameter);
    }
}
